from pathlib import Path

SOURCE = Path("src/mod_npcchat.cpp")
text = SOURCE.read_text(encoding="utf-8")


def replace_region(source: str, start_marker: str, end_marker: str, replacement: str) -> str:
    start = source.find(start_marker)
    if start < 0:
        raise RuntimeError(f"start marker not found: {start_marker!r}")
    end = source.find(end_marker, start + len(start_marker))
    if end < 0:
        raise RuntimeError(f"end marker not found after start: {end_marker!r}")
    return source[:start] + replacement + source[end:]


text = replace_region(
    text,
    "    // --- lazy config (NpcChat.Bot.*) -------------------------------------------\n",
    "    // --- race / class / gender text --------------------------------------------\n",
    '''    // --- config (NpcChat.Bot.*) ------------------------------------------------\n    // Read these values when a conversation is dispatched so `.npcc reload` applies\n    // immediately. Character cards themselves are always read fresh from disk.\n    struct BotCfg\n    {\n        bool        enable = false;\n        bool        replyWhisper = true;\n        bool        replyPartyRaid = true;\n        bool        replyTarget = true;\n        float       triggerRange = 25.0f;\n        int         historyTail = 20;\n        std::string characterCardsPath = "./characters";\n    };\n\n    inline BotCfg GetBotCfg()\n    {\n        BotCfg cfg;\n        cfg.enable = sConfigMgr->GetOption<bool>("NpcChat.Bot.Enable", false);\n        cfg.replyWhisper = sConfigMgr->GetOption<bool>("NpcChat.Bot.ReplyWhisper", true);\n        cfg.replyPartyRaid = sConfigMgr->GetOption<bool>("NpcChat.Bot.ReplyPartyRaid", true);\n        cfg.replyTarget = sConfigMgr->GetOption<bool>("NpcChat.Bot.ReplyTarget", true);\n        cfg.triggerRange = sConfigMgr->GetOption<float>("NpcChat.Bot.TriggerRange", 25.0f);\n        cfg.historyTail = sConfigMgr->GetOption<int32>("NpcChat.Bot.HistoryMaxLines", 20);\n        cfg.characterCardsPath = sConfigMgr->GetOption<std::string>(\n            "NpcChat.Bot.CharacterCardsPath", "./characters");\n        return cfg;\n    }\n\n'''
)

text = replace_region(
    text,
    "    // --- bot file paths (mirror your NPC shared/personal layout) ---------------\n",
    "    // --- cross-thread structs / queue ------------------------------------------\n",
    '''    // --- bot character cards + simple per-player history --------------------------\n    // Character identity is name-based on purpose: this matches mod-playerbots-characters\n    // (`characters/ExactCharacterName.card.txt`) and survives bot GUID changes.\n    // GUIDs remain useful for private conversation history only.\n    inline std::string BotBase(std::string const& botName, uint64_t botGuidRaw)\n    {\n        return SanitizeName(botName) + "_" + std::to_string(botGuidRaw);\n    }\n\n    inline std::string BotCharacterCardFilePath(std::string const& botName)\n    {\n        return (std::filesystem::path(GetBotCfg().characterCardsPath) /\n            (botName + ".card.txt")).string();\n    }\n\n    inline std::string BotPersonalHistoryFilePath(std::string const& playerName, uint64_t playerGuidRaw,\n        std::string const& botName, uint64_t botGuidRaw)\n    {\n        return g_HistoryPath + "/bots/personal/" + PlayerHistoryBase(playerName, playerGuidRaw) +\n            "/" + BotBase(botName, botGuidRaw) + ".history";\n    }\n\n    inline void EnsureBotChatDirectories()\n    {\n        try\n        {\n            std::filesystem::create_directories(GetBotCfg().characterCardsPath);\n            std::filesystem::create_directories(g_HistoryPath + "/bots/personal");\n        }\n        catch (std::exception const&) {}\n    }\n\n'''
)

text = replace_region(
    text,
    "    // One-time shared identity card, generated from the bot's real character.\n",
    "    inline std::string BuildBotUserPrompt(BotChatRequest const& req, std::deque<std::string> const& history)\n",
    '''    // PBC-compatible starter file. This is deliberately NOT generated by an LLM.\n    // It exists only so every bot gets an immediately editable character card on first contact.\n    inline std::string BuiltInBotCharacterCardTemplate()\n    {\n        return\n            "You are {char_name}, a {char_gender} {char_race} {char_class}.\\n\\n"\n            "You are an adventurer living in Azeroth. Your personality, background, mannerisms, "\n            "beliefs, likes, dislikes, and relationships can be described here.\\n\\n"\n            "Stay in character when speaking.";\n    }\n\n    // Caller holds g_FileMutex. Read the card every conversation so a manual edit is\n    // visible on the very next line the bot speaks. Never overwrite an existing file.\n    inline std::string LoadBotCharacterCard(std::string const& botName)\n    {\n        std::string const path = BotCharacterCardFilePath(botName);\n        std::string card = ReadWholeTextFile(path);\n\n        if (card.empty())\n        {\n            WriteWholeTextFile(path, BuiltInBotCharacterCardTemplate(), false);\n            card = ReadWholeTextFile(path);\n        }\n\n        // If the path cannot be written (or an intentionally empty file exists),\n        // still give the current conversation the harmless built-in template.\n        return card.empty() ? BuiltInBotCharacterCardTemplate() : card;\n    }\n\n    inline std::string ExpandBotCharacterCard(BotChatRequest const& req, std::string card)\n    {\n        ReplaceAllInPlace(card, "{char_name}", req.botName);\n        ReplaceAllInPlace(card, "{char_gender}", req.botGender);\n        ReplaceAllInPlace(card, "{char_race}", req.botRace);\n        ReplaceAllInPlace(card, "{char_class}", req.botClass);\n        ReplaceAllInPlace(card, "{char_level}", std::to_string(req.botLevel));\n        return card;\n    }\n\n    inline std::string BuildBotSystemPrompt(BotChatRequest const& req,\n        std::string const& characterCard)\n    {\n        std::ostringstream ss;\n        ss << "You are " << req.botName << ", " << BuildBotPersona(req)\n            << ", adventuring in Azeroth (World of Warcraft) as a companion to fellow players.\\n";\n        if (!characterCard.empty())\n            ss << "\\nCharacter card:\\n" << characterCard << "\\n";\n        ss << "Stay fully in character. Use only your own spoken words: no narration, no "\n            "asterisks, no out-of-character text, no game mechanics. Keep replies to one or "\n            "two short sentences suitable for a single line of in-game chat.";\n        return ss.str();\n    }\n\n'''
)

text = replace_region(
    text,
    "    inline void BotWorkerRun(BotChatRequest req)\n",
    "    // Capture bot/player data on the MAIN THREAD, then hand the worker only copies.\n",
    '''    inline void BotWorkerRun(BotChatRequest req)\n    {\n        std::string const historyPath = BotPersonalHistoryFilePath(\n            req.playerName, req.playerGuidRaw, req.botName, req.botGuidRaw);\n        BotCfg const cfg = GetBotCfg();\n\n        std::deque<std::string> history;\n        std::string characterCard;\n\n        {\n            std::lock_guard<std::mutex> lock(g_FileMutex);\n            EnsureBotChatDirectories();\n            characterCard = LoadBotCharacterCard(req.botName);\n            history = LoadHistoryTail(historyPath, cfg.historyTail);\n            AppendHistoryLine(historyPath, req.playerName + ": " + req.message);\n        }\n\n        characterCard = ExpandBotCharacterCard(req, std::move(characterCard));\n\n        NpcChat_ApiConfig apiCfg = BuildChatApiConfig();\n        NpcChat_LLMResult res = NpcChat_CallLLM(apiCfg,\n            BuildBotSystemPrompt(req, characterCard),\n            BuildBotUserPrompt(req, history));\n\n        if (!res.success || res.text.empty())\n            return;\n\n        {\n            std::lock_guard<std::mutex> lock(g_FileMutex);\n            AppendHistoryLine(historyPath, req.botName + ": " + res.text);\n        }\n\n        BotChatReply reply;\n        reply.playerGuidRaw = req.playerGuidRaw;\n        reply.botGuidRaw = req.botGuidRaw;\n        reply.channel = req.channel;\n        reply.text = res.text;\n\n        std::lock_guard<std::mutex> lock(BotReplyMutex());\n        BotReplyQueue().push(std::move(reply));\n    }\n\n'''
)

text = replace_region(
    text,
    "    // --- config (lazy) ---------------------------------------------------------\n",
    "    // --- cross-thread structs / queue ------------------------------------------\n",
    '''    // --- bot surface config ------------------------------------------------------\n    // Like BotCfg, read on use so `.npcc reload` is effective for guild/LFG settings.\n    struct BotSurfaceCfg\n    {\n        bool   lfgEnable = true;\n        int    levelBracket = 8;\n        bool   lfgGeneral = true;\n        bool   lfgTrade = false;\n        uint32 ambientChance = 0;    // General ambient reply chance (0 = off)\n        bool   guildEnable = true;\n        int    guildMaxTurns = 4;\n        int    guildWindowSec = 300;\n    };\n\n    inline BotSurfaceCfg GetSurfaceCfg()\n    {\n        BotSurfaceCfg c;\n        c.lfgEnable = sConfigMgr->GetOption<bool>("NpcChat.Bot.Lfg.Enable", true);\n        c.levelBracket = sConfigMgr->GetOption<int32>("NpcChat.Bot.Lfg.LevelBracket", 8);\n        c.lfgGeneral = sConfigMgr->GetOption<bool>("NpcChat.Bot.Lfg.General", true);\n        c.lfgTrade = sConfigMgr->GetOption<bool>("NpcChat.Bot.Lfg.Trade", false);\n        c.ambientChance = sConfigMgr->GetOption<uint32>("NpcChat.Bot.General.Chance", 0);\n        c.guildEnable = sConfigMgr->GetOption<bool>("NpcChat.Bot.Guild.Enable", true);\n        c.guildMaxTurns = sConfigMgr->GetOption<int32>("NpcChat.Bot.Guild.MaxTurns", 4);\n        c.guildWindowSec = sConfigMgr->GetOption<int32>("NpcChat.Bot.Guild.WindowSec", 300);\n        return c;\n    }\n\n'''
)

text = replace_region(
    text,
    "    inline void BotSurfaceWorkerRun(BotSurfaceRequest req)\n",
    "    // Capture on MAIN THREAD, hand the worker copies only.\n",
    '''    inline void BotSurfaceWorkerRun(BotSurfaceRequest req)\n    {\n        std::string const historyPath = BotPersonalHistoryFilePath(\n            req.playerName, req.playerGuidRaw, req.botName, req.botGuidRaw);\n        BotCfg const cfg = GetBotCfg();\n\n        std::deque<std::string> history;\n        std::string characterCard;\n        {\n            std::lock_guard<std::mutex> lock(g_FileMutex);\n            EnsureBotChatDirectories();\n            characterCard = LoadBotCharacterCard(req.botName);\n            history = LoadHistoryTail(historyPath, cfg.historyTail);\n            AppendHistoryLine(historyPath, req.playerName + ": " + req.message);\n        }\n\n        // Reuse the exact same character-card and conversation prompt path as whisper,\n        // target say, party and raid. Guild/LFG only add a small situation hint.\n        BotChatRequest promptReq;\n        promptReq.playerGuidRaw = req.playerGuidRaw;\n        promptReq.playerName = req.playerName;\n        promptReq.botGuidRaw = req.botGuidRaw;\n        promptReq.botName = req.botName;\n        promptReq.botLevel = req.botLevel;\n        promptReq.botGender = req.botGender;\n        promptReq.botRace = req.botRace;\n        promptReq.botClass = req.botClass;\n        promptReq.message = req.message;\n\n        characterCard = ExpandBotCharacterCard(promptReq, std::move(characterCard));\n        std::string systemPrompt = BuildBotSystemPrompt(promptReq, characterCard);\n        if (!req.contextHint.empty())\n            systemPrompt += "\\n\\nCurrent situation:\\n" + req.contextHint;\n\n        NpcChat_LLMResult res = NpcChat_CallLLM(\n            BuildChatApiConfig(), systemPrompt, BuildBotUserPrompt(promptReq, history));\n        if (!res.success || res.text.empty())\n            return;\n\n        {\n            std::lock_guard<std::mutex> lock(g_FileMutex);\n            AppendHistoryLine(historyPath, req.botName + ": " + res.text);\n        }\n\n        BotSurfaceReply rep;\n        rep.playerGuidRaw = req.playerGuidRaw;\n        rep.botGuidRaw = req.botGuidRaw;\n        rep.kind = req.kind;\n        rep.channelName = req.channelName;\n        rep.text = res.text;\n\n        std::lock_guard<std::mutex> lock(SurfaceReplyMutex());\n        SurfaceReplyQueue().push(std::move(rep));\n    }\n\n'''
)

text = text.replace("BotCfg const& cfg = GetBotCfg();", "BotCfg const cfg = GetBotCfg();")
text = text.replace("BotSurfaceCfg const& cfg = GetSurfaceCfg();", "BotSurfaceCfg const cfg = GetSurfaceCfg();")

for forbidden in (
    "GenerateBotSharedCard",
    "BotSharedCardFilePath",
    "BotPersonalCardFilePath",
    "generateSharedCard",
    "NpcChat.Bot.GenerateSharedCard",
):
    if forbidden in text:
        raise RuntimeError(f"old generated-card implementation remains: {forbidden}")

required = (
    "NpcChat.Bot.CharacterCardsPath",
    "BotCharacterCardFilePath",
    "BuiltInBotCharacterCardTemplate",
    "LoadBotCharacterCard(req.botName)",
    "ExpandBotCharacterCard",
    "characters/ExactCharacterName.card.txt",
)
for needle in required:
    if needle not in text:
        raise RuntimeError(f"required new implementation missing: {needle}")

SOURCE.write_text(text, encoding="utf-8")
print("Applied simple PBC-compatible playerbot character-card patch.")
